---
title: "Conclusion"
bibliography: references.bib
output: html_document
---

```{=html}
<style>
body {
  text-align: justify;
  font-family: Times;
}

h1, .h1, h2, .h2, h3, .h3 {
  margin-top: 24px;
  font-family: Times;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Conclusion

Now to return to the two research questions, starting with research question one; to what extent do sociologists in the Netherlands display a greater likelihood to collaborate with colleagues affiliated with the same graduate school, compared to colleagues affiliated with a different graduate school?	
	Based on the analyses, which compared between sociologists associated with the graduate school ICS and those not affiliated with this graduate school, the answer to the first research question seems to be no. There is no tendency to collaborate more with others who are affiliated with the same graduate school. This tendency does at first appear to be present, but the reason that sociologists tend to collaborate more with colleagues affiliated with the same graduate school is because graduate schools are in turn affiliated with the sociology departments of specific universities. So sociologists collaborate more with colleagues with whom they share a department, and the tendency to prefer others with the same graduate school is a result of this within department collaboration. 	
 	However, this conclusion should be interpreted with a caveat in mind. The analyses only included one graduate school, ICS, this was done because ICS is attached to three out of seven sociology departments in the Netherlands and about one third of the sociologists in the data, so it represents a considerable proportion of sociologists in the Netherlands. The other reason was theoretical, namely that ICS teaches one of the two prominent research traditions in Dutch sociology [@Haan], the other tradition could then be left implicit, since there are two. Though these reasons to distinguish only between ICS and non-ICS instead of including all graduate schools were carefully considered, it could be that the different non-ICS graduate schools are more heterogenous than assumed. This could lead to an underestimation of the effect, since non-ICS affiliates would not show a much stronger tendency to collaborate with other non-ICS affiliates, even if they do have this tendency towards only the affiliates of their specific graduate school. This is why we cannot conclude with complete certainty that there is no tendency to collaborate with others from the same graduate school at all, but the overall conclusion that the department one works at makes a greater difference still holds. 	
	Then considering the second research question; to what extent does the tendency to work with colleagues from the same graduate school cause clustering in the network of sociologists in the Netherlands? The answer to this question is also no, there is no clustering in the network caused by a preference to collaborate within graduate schools. Considering the potential risks of such clustering for the furthering of scientific knowledge as briefly described in the introduction, this result can be considered a positive indicator for the state of sociology in the Netherlands. The problem of fragmentation into separate research traditions being worsened by the formation of tradition specific graduate schools is not reflected in the results of this study. It should be noted, however, that this does not concluded whether or not there is significant clustering in the collaboration network of sociologists in the Netherlands, since that would require a different kind of analysis. 	
	Overall, the influence of graduate school affiliations on the research collaboration network of Dutch sociologists was not as strong as was anticipated. Future research may consider whether the theoretical or methodological preferences of sociologists have an effect on who they collaborate with, independent of topical interests. This appears a logical next step in unravelling the way the two distinct research traditions in Dutch sociology give shape to the collaboration behaviour and network structure of collaborations among Dutch sociologists, even if the influence of graduate schools is unimportant when university affiliation is accounted for.  


