---
title: "Introduction"
author: "Tjeu Groothuijsen"
date: "2025-09-17"
output: html_document
bibliography: references.bib
---

The previous page already illustrated how I got to these research questions, now to
elaborate on why this matters. The research questions are:

1. Does clustering occur in our data?

2. Is the clustering caused by grad school affiliation?

The ideas people have depend in part on the ideas that are prevalent in their network. 
This is also the case for social scientists[@Moody]. There is a wide variety of schools
of thought, theoretically and methodologically the social sciences are definitely
pluralist, if not multiparadigmatic [@Raub]. For the advancement of knowledge, this
variety has certain advantages and disadvantages. In my opinion, multiple researchers
taking multiple theoretical approaches to the same problem can lead to a more rigorous
theoretical explanation than multiple researchers all using the same approach, so this
pluralism should allow for the development of better theory. However, if the researchers
only come into contact with researchers and studies which use the same approach they
themselves already use, this advantage is lost and fragmentation of the field could 
occur instead. So, if social scientists are to make optimal use of intradisciplinary
pluralism, they must be aware of the dividing lines within their discipline and 
willing to cross them to seek out answers to questions their own perspective may only
partially answer.
From this previous section, the importance of a social network perspective may already be
apparent. The potential problem of fragmentation of a discipline is in large part defined
by the properties of networks of scientists, namely whether there exist groups with
internally homogenous theoretical and/or methodological preferences and the extent
to which membership in one of these groups defines with whom a scientists collaborates.
Graduate school affiliation is sort of a proxy, can this be helped? i.e., can we instead
measure theoretical and/or methodological preferences?

data demands:
node: 
  -grad school affiliation
  -department affiliation
  -
edge:
  -collaboration
  -
